import sprite_market from '../images/sprite_market.svg';
export let postsListData = [
  {
    postId: '101-2222',
    postType: 'look',
    postAutorId: '101',
    postName: 'Сукня, шовкова, синя',
    articul: '00001',
    section: '',
    category: '',
    subCategory: '',
    price: 2256,
    currency: 'UAH',
    cashbackLvl: '02',
    mainAtribute_1: 'синій',
    mainAtribute_2: 'M',
    style: 'night-life',
    content: 'шовк 100%',
    availability: 'у наявності',
    stock: 5,
    manufacturingTime: 2,
    mainImgLink:
      'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/brand_2/suknia-synia__br2.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '101-5555',
    postType: 'look',
    postAutorId: '101',
    postName: 'Сукня, шовкова, рожева',
    articul: '000002',
    section: '',
    category: '',
    subCategory: '',
    price: 2552,
    currency: 'UAH',
    cashbackLvl: '01',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink:
      'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/brand_2/suknia_rozeva_br2.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '101-8888',
    posttype: 'look',
    postAutorId: '101',
    postName: 'Сукня, шовкова, зелена',
    articul: '00003',
    section: '',
    category: '',
    subCategory: '',
    price: 1556,
    currency: 'UAH',
    cashbackLvl: '02',
    mainAtribute_1: {
      atributeName: 'Колір',
      atributeValue: 'Зелений',
    },
    mainAtribute_2: {
      atributeName: 'Розмір',
      atributeValue: 'xl',
    },
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink:
      'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/brand_2/suknia_zelena__br2.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
    ],
    post: 1,
  },
  {
    postId: '102-2222',
    posttype: 'look',
    postAutorId: '102',
    postName: 'Добротна така сукенька',
    articul: '454545',
    section: '',
    category: '',
    subCategory: '',
    price: 568,
    currency: 'UAH',
    cashbackLvl: '03',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: 'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/suknia_3/br-3_f-1.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '102-5555',
    posttype: 'look',
    postAutorId: '102',
    postName: 'Арабський мангуст',
    articul: '453265',
    section: '',
    category: '',
    subCategory: '',
    price: 542,
    currency: 'UAH',
    cashbackLvl: '01',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: 'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/suknia_3/br-3_f-5.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '102-8888',
    posttype: 'look',
    postAutorId: '102',
    postName: 'Плаття на забаву',
    articul: '121212',
    section: '',
    category: '',
    subCategory: '',
    price: 865,
    currency: 'UAH',
    cashbackLvl: '01',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: 'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/suknia_3/br-3_f-9.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '103-2222',
    posttype: 'look',
    postAutorId: '103',
    postName: 'Гаманець',
    articul: '282828',
    section: '',
    category: '',
    subCategory: '',
    price: 456,
    currency: 'UAH',
    cashbackLvl: '02',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: 'https://raw.githubusercontent.com/goodcat46/images/main/gamanets/AW22-PFD08E_99X_F1.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-5555',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '102-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '103-5555',
    posttype: 'look',
    postAutorId: '103',
    postName: 'Ще один гаманець',
    articul: '949494',
    section: '',
    category: '',
    subCategory: '',
    price: 325,
    currency: 'UAH',
    cashbackLvl: '01',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: 'https://raw.githubusercontent.com/goodcat46/images/main/gamanets/AW22-AKD0FM_80X_F1.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '103-8888',
    posttype: 'look',
    postAutorId: '103',
    postName: 'Знову гаманець',
    articul: '353535',
    section: '',
    category: '',
    subCategory: '',
    price: 259,
    currency: 'UAH',
    cashbackLvl: '03',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: 'https://raw.githubusercontent.com/goodcat46/images/main/gamanets/AW22-PFD08E_88X_F1.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '102-2222',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '103-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '104-2222',
    posttype: 'look',
    postAutorId: '104',
    postName: '',
    articul: '494949',
    section: '',
    category: '',
    subCategory: '',
    price: 478,
    currency: 'UAH',
    cashbackLvl: '02',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: '',
    imagesList: [],
    postItemList: [
      {
        itemId: '102-2222',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '103-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '104-5555',
    posttype: 'look',
    postAutorId: '104',
    postName: 'Сорочка',
    articul: '646869',
    section: '',
    category: '',
    subCategory: '',
    price: 352,
    currency: 'UAH',
    cashbackLvl: '03',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: '',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '102-5555',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '104-8888',
    posttype: 'look',
    postAutorId: '104',
    postName: 'Сорочка',
    articul: '159564',
    section: '',
    category: '',
    subCategory: '',
    price: 356,
    currency: 'UAH',
    cashbackLvl: '03',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink: '',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '102-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
  {
    postId: '105-2222',
    postType: 'look',
    postAutorId: '105',
    postName: 'Сукня, шовкова, синя',
    articul: '00025',
    section: '',
    category: '',
    subCategory: '',
    price: 2256,
    currency: 'UAH',
    cashbackLvl: '02',
    mainAtribute_1: '',
    mainAtribute_2: '',
    style: '',
    content: '',
    availability: '',
    stock: '',
    manufacturingTime: '',
    mainImgLink:
      'https://raw.githubusercontent.com/goodcat46/images/main/brand_cards/suknia-synia/suknia-synia_1.webp',
    imagesList: [],
    postItemList: [
      {
        itemId: '101-8888',
        itemPosTop: '50%',
        itemPostLeft: '28%',
      },
      {
        itemId: '104-8888',
        itemPosTop: '60%',
        itemPostLeft: '20%',
      },
    ],
    post: 1,
  },
];
